source "http://rubygems.org"
ruby '2.2.3'

gem "sinatra"
gem "open_uri_redirections"
gem "trans-api", github: "dblommesteijn/trans-api"
gem "mysql2", '~> 0.4.4'
gem "jwt", '1.5.4'
gem "oauth2"
gem "nokogiri", '1.6.8'
